import PptxGenJS from "pptxgenjs";

interface SlideData {
  title: string;
  bullets: string[];
  speakerNotes: string;
}

/**
 * Parse the text-based presentation format into structured slides
 */
export function parsePresentationText(text: string): SlideData[] {
  const slides: SlideData[] = [];
  const slideBlocks = text.split(/SLIDE \d+ —/g).filter((b) => b.trim());

  for (const block of slideBlocks) {
    const lines = block.split("\n").filter((l) => l.trim());
    const titleLine = lines[0]?.replace(/^.*?—\s*/, "").trim() || "";
    const title = titleLine.replace(/━+/g, "").trim();

    const bullets: string[] = [];
    let speakerNotes = "";
    let inSpeakerNotes = false;

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.startsWith("Speaker Notes:")) {
        inSpeakerNotes = true;
        const noteText = line.replace("Speaker Notes:", "").trim();
        if (noteText) speakerNotes = noteText.replace(/^[""]|[""]$/g, "");
        continue;
      }
      if (line.startsWith("━")) continue;
      if (line.startsWith("Title:")) continue;
      if (inSpeakerNotes) {
        speakerNotes += " " + line.replace(/^[""]|[""]$/g, "");
      } else if (line.startsWith("•") || line.startsWith("-") || line.startsWith("Key")) {
        bullets.push(line.replace(/^•\s*/, "").replace(/^-\s*/, ""));
      }
    }

    if (title) {
      slides.push({ title, bullets, speakerNotes: speakerNotes.trim() });
    }
  }

  return slides;
}

/**
 * Generate a real .pptx file and trigger download
 */
export async function generatePptx(
  title: string,
  content: string
): Promise<void> {
  const pptx = new PptxGenJS();
  const slides = parsePresentationText(content);

  // Set presentation metadata
  pptx.title = title;
  pptx.author = "TransformAI";
  pptx.subject = "Generated Presentation";
  pptx.layout = "LAYOUT_WIDE";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "4F46E5" };
  titleSlide.addText(title, {
    x: 0.8,
    y: 1.5,
    w: 11.6,
    h: 2,
    fontSize: 36,
    fontFace: "Arial",
    color: "FFFFFF",
    bold: true,
    align: "center",
  });
  titleSlide.addText("Generated by TransformAI", {
    x: 0.8,
    y: 3.8,
    w: 11.6,
    h: 0.6,
    fontSize: 14,
    fontFace: "Arial",
    color: "C7D2FE",
    align: "center",
  });
  titleSlide.addText(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), {
    x: 0.8,
    y: 4.4,
    w: 11.6,
    h: 0.5,
    fontSize: 12,
    fontFace: "Arial",
    color: "A5B4FC",
    align: "center",
  });

  // Content slides
  for (const slide of slides) {
    const s = pptx.addSlide();

    // Background
    s.background = { color: "FFFFFF" };

    // Top accent bar
    s.addShape("rect" as any, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.06,
      fill: { color: "4F46E5" },
    });

    // Slide title
    s.addText(slide.title, {
      x: 0.8,
      y: 0.4,
      w: 11.6,
      h: 0.8,
      fontSize: 28,
      fontFace: "Arial",
      color: "1E293B",
      bold: true,
    });

    // Divider line under title
    s.addShape("rect" as any, {
      x: 0.8,
      y: 1.25,
      w: 2.5,
      h: 0.04,
      fill: { color: "4F46E5" },
    });

    // Bullet points
    const bulletTexts = slide.bullets.map((b) => ({
      text: b,
      options: {
        fontSize: 16,
        fontFace: "Arial",
        color: "334155",
        bullet: { code: "2022", color: "4F46E5" },
        paraSpaceAfter: 8,
        lineSpacingMultiple: 1.3,
      },
    }));

    if (bulletTexts.length > 0) {
      s.addText(bulletTexts, {
        x: 0.8,
        y: 1.5,
        w: 11.6,
        h: 4.5,
        valign: "top",
      });
    }

    // Speaker notes
    if (slide.speakerNotes) {
      s.addNotes(slide.speakerNotes);
    }

    // Footer
    s.addText("TransformAI", {
      x: 0.8,
      y: 6.8,
      w: 3,
      h: 0.4,
      fontSize: 9,
      fontFace: "Arial",
      color: "94A3B8",
    });
  }

  // Generate and download
  const blobResult = await pptx.write({ outputType: "blob" });
  const blob = blobResult instanceof Blob
    ? blobResult
    : new Blob([new Uint8Array(blobResult as ArrayBuffer)], { type: "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9]/g, "_")}.pptx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
